
package carArchiveService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarArchiveServiceImplService", targetNamespace = "http://impl.car.service.oa.htsoft.com/", wsdlLocation = "http://192.168.7.8:80/jofficesrc/webservice/carArchiveService?wsdl")
public class CarArchiveServiceImplService
    extends Service
{

    private final static URL CARARCHIVESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARARCHIVESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CARARCHIVESERVICEIMPLSERVICE_QNAME = new QName("http://impl.car.service.oa.htsoft.com/", "CarArchiveServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.7.8:80/jofficesrc/webservice/carArchiveService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARARCHIVESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CARARCHIVESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CarArchiveServiceImplService() {
        super(__getWsdlLocation(), CARARCHIVESERVICEIMPLSERVICE_QNAME);
    }

    public CarArchiveServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARARCHIVESERVICEIMPLSERVICE_QNAME, features);
    }

    public CarArchiveServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CARARCHIVESERVICEIMPLSERVICE_QNAME);
    }

    public CarArchiveServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARARCHIVESERVICEIMPLSERVICE_QNAME, features);
    }

    public CarArchiveServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarArchiveServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarArchiveService
     */
    @WebEndpoint(name = "CarArchiveServiceImplPort")
    public CarArchiveService getCarArchiveServiceImplPort() {
        return super.getPort(new QName("http://impl.car.service.oa.htsoft.com/", "CarArchiveServiceImplPort"), CarArchiveService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarArchiveService
     */
    @WebEndpoint(name = "CarArchiveServiceImplPort")
    public CarArchiveService getCarArchiveServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.car.service.oa.htsoft.com/", "CarArchiveServiceImplPort"), CarArchiveService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARARCHIVESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CARARCHIVESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CARARCHIVESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
