
package carArchiveService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarArchiveService", targetNamespace = "http://car.service.oa.htsoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarArchiveService {


    /**
     * 
     * @return
     *     returns java.util.List<carArchiveService.CarArchive>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAll", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.ListAll")
    @ResponseWrapper(localName = "listAllResponse", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.ListAllResponse")
    public List<CarArchive> listAll();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<carArchiveService.CarArchive>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPageAll", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.ListPageAll")
    @ResponseWrapper(localName = "listPageAllResponse", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.ListPageAllResponse")
    public List<CarArchive> listPageAll(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<carArchiveService.CarArchive>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByCarnumber", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.GetByCarnumber")
    @ResponseWrapper(localName = "getByCarnumberResponse", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.GetByCarnumberResponse")
    public List<CarArchive> getByCarnumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<carArchiveService.CarArchive>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarArchiveByEquips", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.GetCarArchiveByEquips")
    @ResponseWrapper(localName = "getCarArchiveByEquipsResponse", targetNamespace = "http://car.service.oa.htsoft.com/", className = "carArchiveService.GetCarArchiveByEquipsResponse")
    public List<CarArchive> getCarArchiveByEquips(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
